const constants = {
    ADD_QUESTION: "ADD_QUESTION",
    REMOVE_QUESTION: "REMOVE_QUESTION",
    SET_SELECTED_ANSWER: "SET_SELECTED_ANSWER",
    ON_SELECT_ANSWER: "ON_SELECT_ANSWER",
    FETCH_QUESTIONS: "FETCH_QUESTIONS",
    CANCEL_FETCH_QUESTIONS: "ON_FETCH_QUESTIONS",
    SET_SCORE: "SET_SCORE",
    SET_PROGRESS_COUNTER: "SET_PROGRESS_COUNTER"

}

export default constants;